### ISSUE TITLE
json indexing

### ISSUE THREAD

**Issue by goldalworming** [petersirka/node-fulltext#1]
I tried to index the text use json but it doesn't work..

var id1 = fulltext.add('{ title: "Blog 01", created: udsflj, yo : ha }', { title: 'Blog 01', created: new Date() });
var id2 = fulltext.add('{ title: " Blog 02 ", created: udsflj, yo : ya }', { title: 'Blog 02', created: new Date() });

and it case sensitive, so when I want to search blog 2..it doesn't work..

**Comment by petersirka** [comment]
Hi @goldalworming,
try to use:

``` js
var id1 = fulltext.add('{ title: "Blog 01", created: udsflj, yo : ha }', { title: 'Blog 01', created: new Date() });
var id2 = fulltext.add('{ title: " Blog 02 ", created: udsflj, yo : ya }', { title: 'Blog 02', created: new Date() });

setTimeout(function() {
    fulltext.find('blog 2', {}, function(count, docs) {
        console.log(docs);
    });
}, 200);
```

Problem was not found.

**Comment by goldalworming** [comment]
I got this results
[ { id: '1387796994880',
    document: { title: 'Blog 02', created: '2013-12-23T11:09:54.880Z' } },
  { id: '1387796994873',
    document: { title: 'Blog 01', created: '2013-12-23T11:09:54.872Z' } },
  { id: '1387796956972',
    document: { title: 'Blog 02', created: '2013-12-23T11:09:16.972Z' } },
  { id: '1387796956965',
    document: { title: 'Blog 01', created: '2013-12-23T11:09:16.965Z' } },
  { id: '1387792474499',
    document: { title: 'Blog 01', created: '2013-12-23T09:54:34.499Z' } },
  { id: '1387792377604',
    document: { title: 'Blog 01', created: '2013-12-23T09:52:57.604Z' } },
  { id: '1387792487280',
    document: { title: 'Blog 01', created: '2013-12-23T09:54:47.279Z' } },
  { id: '1387792328748',
    document: { title: 'Blog 01', created: '2013-12-23T09:52:08.747Z' } },
  { id: '1387792512566',
    document: { title: 'Blog 01', created: '2013-12-23T09:55:12.565Z' } },
  { id: '1387792505617',
    document: { title: 'Blog 01', created: '2013-12-23T09:55:05.617Z' } } ]

from this file

1387792328748,mi,first,blog
1387792328755,mi,second,blog
1387792377604,mi,first,blog
1387792377611,mi,second,blog
1387792474499,mi,first,blog
1387792474506,mi,second,blog
1387792487280,mi,first,blog
1387792487287,mi,second,blog
1387792505617,mi,first,blog
1387792505624,mi,second,blog
1387792512566,mi,first,blog
1387792512573,mi,second,blog
1387796956965,title,blog,01,created,udsflj,io,ha
1387796956972,title,blog,02,created,udsflj,io,ia
1387796994873,title,blog,01,created,udsflj,io,ha
1387796994880,title,blog,02,created,udsflj,io,ia
1387957219764,title,blog,01,created,udsflj,io,ha
1387957219771,title,blog,02,created,udsflj,io,ia

I think them last one with id 1387957219771 should appear first because of hit point and the timestamp..

do you have strict option mode??

**Comment by petersirka** [comment]
You must save FULLTEXT id in the blog document. Then if you will update a blog you should update fulltext document via fulltext id.

Fulltext parses minimum 2 char length word because if you'll search **Blog 2** fulltext will really search _{Blog}__. If you'll search **Blog 02** fulltext will search **{Blog} {02}**.

Thanks.

**Comment by goldalworming** [comment]
ok..it works...
this is very cool engine peter

thanks for your beautifull work
