### ISSUE TITLE
data more than 20 000

### ISSUE THREAD

**Issue by goldalworming** [petersirka/node-fulltext#3]
I have data more than 20000 to index (about 540 000)..how to make it work with node-fulltext

I plan to make subfolder of each category

-/company
--/company/1
--/company/2
--/company/3
--/company/4

-/user
--/user/1
--/user/2
--/user/3

what do you think about this approach? is it going to have performance issue??

**Comment by petersirka** [comment]
Try to add 540 000 records ... I don't know what happens :-) ... but we must test it.
In which database do you have stored data?

PS:
node-fulltext contains delegates for manipulation with the data. I must add them into the documentation.

**Comment by goldalworming** [comment]
we store in oracle but going to export to mysql.. 
as using angular we got confuse of searching in server side that maybe only could handle by fts..

**Comment by goldalworming** [comment]
what's make you limit of 20 000 data??
something I don't understand is why you should store data inside folder?

since you have made nosql database and we usually use another existing database, why don't you just return the id  of inserted value

like
var id1 = fulltext.add('My first blog', { title: 'Blog 01', created: new Date() });
why is it store { title: 'Blog 01', created: new Date() } in json file??

why don't you save 
var id1 = fulltext.add('My first blog, foo bar', 'nosql-id');
var id2 = fulltext.add('My second blog, foo bar', 'nosql-id2');
so when we search 'foo bar' it return ['nosql-id','nosql-id2'] then we search in nosql database use returned id

so we don't have to store whole database to full text search..

**Comment by petersirka** [comment]
**what's make you limit of 20 000 data?**
This is my tip only :-)

**Something I don't understand is why you should store data inside folder?**
Because  HDD is a good database which stores data without database :-)

**why don't you save**
Because node-fulltext has nothing to do with NoSQL embedded database :-)

I'll add delegates into the "documentation" and you can rewrite basic functionality.
